### ISSUE TITLE
Cluster Config File

### ISSUE THREAD

**Issue by noxify** [rinvex/extensions#2]
Hi,

currently i'm testing the extensions package.

While I'm searching the function to get all existing extensions i found the following code:

```php
if ($container['config']->get('cluster.route.locale_prefix')) {
```
https://github.com/rinvex/extensions/blob/develop/src/Extension.php#L701

Didn't found any config named "cluster".

It looks like that it's related to your cluster package.

**Comment by Omranic** [comment]
Yup, it is. I believe the whole condition is messy and maybe requires rewrite from scratch. But it's functional at the moment, and the cluster package coming out this month.

**Comment by noxify** [comment]
perfect - Thanks for the fast feedback and for publishing the awesome packages.

Is cluster the open source alternative to platform?


FYI: It works perfect with laravel 5.2.

Thanks a lot.

**Comment by Omranic** [comment]
Yes, it is :smiley: 
Thanks for the feedback :+1:

**Comment by noxify** [comment]
Before I forgot to go to sleep my last words for this evening.

The packages are awesome - currently I'm using the Cartalyst documentation even when I have some problems...

But these packages were the first one which works like a charme :)

Thanks again @Omranic 

Btw. I pushed my current tests to a Repo: https://github.com/Pseudoagentur/rinvex-example

In my tests I will build a example extension manager to handle the existing extensions...

Don't know what you have already implemented, but to dive deeper it's a good exercise :)

Good night :)

**Comment by Omranic** [comment]
Sounds cool, keep moving forward :+1: 
Can't wait to see what the community will do with these packages once it's all out, stable and works in harmony together. The best yet to come..

P.S. Docs are being written currently and will start to appear soon within a week.

**Comment by noxify** [comment]
Sounds good :)

If you want, I can move my code from docs.pseudoagentur.de from bitbucket to Github.

It's based on docit and the lravel documentation theme.

It's include also a separate github sync command.

Let me know, if you're interested.
