### ISSUE TITLE
Question: How to load extensions via composer

### ISSUE THREAD

**Issue by noxify** [rinvex/extensions#4]
Hi,

how can I change the way to load the extensions?

If I'm not wrong, it's only possible to load it via the `extensions.php`.
But i saw in your code, that there are some config values, where you can define how to load the extensions (via "cluster", "composer"...)

Is this currently implemented in the rinvex/extensions package or only in cluster?

Thanks.

**Comment by Omranic** [comment]
Hello Marcus,

You're correct, you can change autoloading through your extension.php 'autoload' key, and you've three options: 'composer' (default & recommended), 'cluster', and Closure. And yes, it's currently implemented through "rinvex/extensions" package.

To know more about how it works check out the following lines: https://github.com/rinvex/extensions/blob/develop/src/Extension.php#L636-L648

Regards
